### PR TITLE
Fix usage of octet in recent patch

### PR DESCRIPTION
**Pull request by cjobeili**
Fix octet usage of #181 

Octet: https://3v4l.org/lHLUE
Short: https://3v4l.org/TbfAJ

### CODE REVIEW

**Comment by j0k3r** [comment]
@vendethiel @mentalstring Are you ok with that extra fix?

**Comment by vendethiel** [comment]
Seems good to me.

**Comment by mentalstring** [comment]
The casting on the return is now unnecessary (ie: $value is casted twice to int), but this is nitpicking — it works fine like this.

**Comment by j0k3r** [comment]
Thanks @cjobeili!

**Pull request merged**
