### PR TITLE
fixed missing release

### PR DESCRIPTION
**Pull request by issei-m**
@GromNaN Thanks for releasing 1.5.5. It's great! but seems to be missing a few things:
- Updating Changelog
- Bumping version number

### CODE REVIEW

**Comment by GromNaN** [comment]
Arf, do you think I can re-create the release ?

/cc @j0k3r

**Comment by issei-m** [comment]
@GromNaN I'm not sure which is best, re-create or new release (i.e. release 1.5.6)

A long time ago, Symfony 2.0.3 was released soon after 2.0.2 was released to revert fatal bug:
http://symfony.com/blog/symfony-2-0-3-released
Just for reference.

**Comment by mentalstring** [comment]
I know this is off-topic, but if you are considering to re-release, please see https://github.com/LExpress/symfony1/commit/cbf0fc04a5ff7576a6faed45f4a7e21339886051#commitcomment-12067620 and consider reverting https://github.com/LExpress/symfony1/commit/570dd07f610dca46846f6e6a29692f7304fcd4fe which effectively made sfAPCCache incompatible with the current version of APCu.

**Comment by GromNaN** [comment]
I'll revert the APCu change (see #99) and make a new release.

**Comment by GromNaN** [comment]
New release: https://github.com/LExpress/symfony1/releases/tag/v1.5.6

**Pull request merged**
