### PR TITLE
Fix/php 7.2 deprecation warnings

### PR DESCRIPTION
**Pull request by e1himself**
This pull replaces `create_function` usages to regular lambda functions (introduced in PHP 5.3) to improve PHP 7.2 compatibility. 

It will fix PHP nightly build compatibility at your Travis-CI output:

### CODE REVIEW

**Comment by e1himself** [comment]
Hm... It means that part is not covered with tests. Alright. I'll fix that as well.

**Comment by j0k3r** [comment]
Yeah, the test suite doesn't cover 100% of the code.
That's why green tests doesn't mean everything will be ok 😕

**Comment by e1himself** [comment]
@j0k3r done!

**Pull request merged**
