### PR TITLE
Update UPGRADE file about configureDoctrine

### LINKED ISSUE #42: Can't use configureDoctrine function anymore
On sf1.4, the following code was inside sfDoctrinePluginConfiguration.class.php  allowing me to use configureDoctrine() inside my ProjectConfiguration.class.php
```
 if (method_exists($this->configuration, 'configureDoctrine')) {
     $this->configuration->configureDoctrine($manager);
 }
```

I understand that now I should use the dispatcher on doctrine.configure event, but for retrocompatibility, it should be back or at least mentionned in migration doc.

### PR DESCRIPTION
**Pull request by j0k3r**
Fix #42 

@faboo03 @cburyta @alex-pex are you ok with that?

### CODE REVIEW

**Comment by alex-pex** [comment]
> You know need to connect [...]

You mean "You **now** need to connect"

**Comment by j0k3r** [comment]
@alex-pex yep.

**Comment by alex-pex** [comment]
thanks :+1:

**Comment by cburyta** [comment]
Awesome!

**Pull request merged**
