### PR TITLE
fix notice "A non well formed numeric value encountered in ... sfValidatorSchema::getBytes" (php 7.1)

### PR DESCRIPTION
**Pull request by zobzn**

### CODE REVIEW

**Comment by j0k3r** [comment]
Hello @zobzn 
Thanks for that. Could you try to add unitest to validate there is no bad behavior introduced?

**Comment by zobzn** [comment]
something like this?

**Comment by j0k3r** [comment]
Awesome, thanks for that.
I just played your test on the actual base code (on PHP 5.6), without your changes on `sfValidatorSchema.class.php` and I got some errors:

```
#   at unit/validator/sfValidatorSchemaTest.php line 422
>   kilobytes long syntax
           got: '1KB'
      expected: 1024
#   at unit/validator/sfValidatorSchemaTest.php line 423
>   kilobytes long syntax with space delimiter
           got: '1 KB'
      expected: 1024
#   at unit/validator/sfValidatorSchemaTest.php line 428
>   terabytes
           got: '1 T'
      expected: 1099511627776
#   at unit/validator/sfValidatorSchemaTest.php line 429
>   petabytes
           got: '1 P'
      expected: 1125899906842624
#   at unit/validator/sfValidatorSchemaTest.php line 430
>   exabytes
           got: '1 E'
      expected: 1152921504606846976
#   at unit/validator/sfValidatorSchemaTest.php line 431
>   zettabytes
           got: '1 Z'
      expected: 1.1805916207174113E+21
#   at unit/validator/sfValidatorSchemaTest.php line 432
>   yottabytes
           got: '1 Y'
      expected: 1.2089258196146292E+24
```

It seems some behavior aren't the same with your change.
Could you try to fix them?

**Comment by zobzn** [comment]
hmm ... according to the documentation (http://php.net/manual/en/faq.using.php#faq.using.shorthandbytes), some tests can simply be removed, since post_max_size may only be used in this formats: n, nB, nM, nG

**Pull request merged**
