### PR TITLE
travis does not use --remote on git submodule update

### PR DESCRIPTION
**Pull request by zkiiito**
so, the tests are running with old versions of doctrine and swiftmailer:

```
Submodule path 'lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine': checked out '3d95c7f506e8b29d8e1fd48573dd0d046b9e6ae6'
Submodule path 'lib/vendor/swiftmailer': checked out '0697e6aa65c83edf97bb0f23d8763f94e3f11421'
```
with this update:

```
Submodule path 'lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine': checked out '7abe498f56d383fabcd92ccc87f5d1a72c47f7f9'
Submodule path 'lib/vendor/swiftmailer': checked out '1460e98b53d2f916f1b4123069c96c90844a1a4d'
```

### CODE REVIEW

**Comment by j0k3r** [comment]
I think it was mostly to avoid testing on updated submobules but rather always use the locked ones.

**Comment by zkiiito** [comment]
yeah it could be, but now it does not test with the versions users pull from composer :(

**Comment by j0k3r** [comment]
Ok it's fine for me.
Could you update the submodule too?

**Comment by zkiiito** [comment]
it's done

**Comment by j0k3r** [comment]
Thanks !

**Pull request merged**
