### PR TITLE
Fix in sfViewConfigHandlerfor php7 compatibility

### PR DESCRIPTION
**Pull request by ibr**
all stylesheets with options were missing
stylesheets:    [main: {media: all}, layout: {position: last},.]

### CODE REVIEW

**Comment by j0k3r** [comment]
Thanks for that.
Is that supposed to fix the test `functional/genericTest`? Or is it related to an other one?

**Comment by ibr** [comment]
I just switched to php7 and run into it.

**Comment by j0k3r** [comment]
Okay, feel free to push other fix for php7 in your branch then.

**Comment by j0k3r** [comment]
PHP 7 compatibility has been done https://github.com/LExpress/symfony1/pull/121

**Pull request closed without merging**
